config/routes.rb
Rails.application.routes.draw do
  get 'blog_list/index'

  get 'archive/index'

  # get 'welcome/index'

  resource :articles

  root 'application#hello'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render text: "Hello world!"
  end

end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
  end

  def create
    render plain:params[:article].inspect
  end

end

app/controllers/blog_list_controller.rb
class BlogListController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_list_helper.rb
module BlogListHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/archive/index.html.erb
<h1>It's blog archive page </h1>
<p>Find me in app/views/archive/index.html.erb</p>

app/views/articles/new.html.erb
<h1>写文章 </h1>

<%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :文章标题 %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :文章内容 %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit :提交 %>
    </p>
<% end %>

app/views/blog_list/index.html.erb
<h1>It's blog list page</h1>
<p>Find me in app/views/blog_list/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails! </h1>